// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef RENDER_STYLE_PROPERTIES_INITIAL_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from RenderStyle+InitialInlines.h."
#endif

#include <WebCore/StyleComputedStyle+InitialInlines.h>

namespace WebCore {

inline constexpr Style::TestEnumeration RenderStyleProperties::initialTestRenderStyleStorageOneLevelEnum()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageOneLevelEnum();
}

inline constexpr Style::TestRaw RenderStyleProperties::initialTestRenderStyleStorageOneLevelRaw()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageOneLevelRaw();
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageOneLevelReference()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageOneLevelReference();
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageOneLevelValue()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageOneLevelValue();
}

inline constexpr Style::TestEnumeration RenderStyleProperties::initialTestRenderStyleStorageTwoLevelEnum()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageTwoLevelEnum();
}

inline constexpr Style::TestRaw RenderStyleProperties::initialTestRenderStyleStorageTwoLevelRaw()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageTwoLevelRaw();
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageTwoLevelReference()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageTwoLevelReference();
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageTwoLevelValue()
{
    return Style::ComputedStyle::initialTestRenderStyleStorageTwoLevelValue();
}

} // namespace WebCore

