// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef RENDER_STYLE_PROPERTIES_GETTERS_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from RenderStyle+GettersInlines.h."
#endif

#include <WebCore/RenderStyleBase+GettersInlines.h>
#include <WebCore/StyleComputedStyle+GettersInlines.h>

namespace WebCore {

inline Style::TestEnumeration RenderStyleProperties::testRenderStyleStorageOneLevelEnum() const
{
    return m_computedStyle.testRenderStyleStorageOneLevelEnum();
}

inline Style::TestRaw RenderStyleProperties::testRenderStyleStorageOneLevelRaw() const
{
    return m_computedStyle.testRenderStyleStorageOneLevelRaw();
}

inline const Style::Number<>& RenderStyleProperties::testRenderStyleStorageOneLevelReference() const
{
    return m_computedStyle.testRenderStyleStorageOneLevelReference();
}

inline Style::Number<> RenderStyleProperties::testRenderStyleStorageOneLevelValue() const
{
    return m_computedStyle.testRenderStyleStorageOneLevelValue();
}

inline Style::TestEnumeration RenderStyleProperties::testRenderStyleStorageTwoLevelEnum() const
{
    return m_computedStyle.testRenderStyleStorageTwoLevelEnum();
}

inline Style::TestRaw RenderStyleProperties::testRenderStyleStorageTwoLevelRaw() const
{
    return m_computedStyle.testRenderStyleStorageTwoLevelRaw();
}

inline const Style::Number<>& RenderStyleProperties::testRenderStyleStorageTwoLevelReference() const
{
    return m_computedStyle.testRenderStyleStorageTwoLevelReference();
}

inline Style::Number<> RenderStyleProperties::testRenderStyleStorageTwoLevelValue() const
{
    return m_computedStyle.testRenderStyleStorageTwoLevelValue();
}

} // namespace WebCore

