// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef RENDER_STYLE_PROPERTIES_SETTERS_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from RenderStyle+SettersInlines.h."
#endif

#include "RenderStyleBase+SettersInlines.h"
#include "StyleComputedStyle+SettersInlines.h"

namespace WebCore {

inline void RenderStyleProperties::setTestRenderStyleStorageOneLevelEnum(Style::TestEnumeration value)
{
    m_computedStyle.setTestRenderStyleStorageOneLevelEnum(value);
}

inline void RenderStyleProperties::setTestRenderStyleStorageOneLevelRaw(Style::TestRaw value)
{
    m_computedStyle.setTestRenderStyleStorageOneLevelRaw(value);
}

inline void RenderStyleProperties::setTestRenderStyleStorageOneLevelReference(Style::Number<>&& value)
{
    m_computedStyle.setTestRenderStyleStorageOneLevelReference(WTF::move(value));
}

inline void RenderStyleProperties::setTestRenderStyleStorageOneLevelValue(Style::Number<> value)
{
    m_computedStyle.setTestRenderStyleStorageOneLevelValue(value);
}

inline void RenderStyleProperties::setTestRenderStyleStorageTwoLevelEnum(Style::TestEnumeration value)
{
    m_computedStyle.setTestRenderStyleStorageTwoLevelEnum(value);
}

inline void RenderStyleProperties::setTestRenderStyleStorageTwoLevelRaw(Style::TestRaw value)
{
    m_computedStyle.setTestRenderStyleStorageTwoLevelRaw(value);
}

inline void RenderStyleProperties::setTestRenderStyleStorageTwoLevelReference(Style::Number<>&& value)
{
    m_computedStyle.setTestRenderStyleStorageTwoLevelReference(WTF::move(value));
}

inline void RenderStyleProperties::setTestRenderStyleStorageTwoLevelValue(Style::Number<> value)
{
    m_computedStyle.setTestRenderStyleStorageTwoLevelValue(value);
}

inline void RenderStyleProperties::setTestLogicalPropertyGroupPhysicalHorizontal(Style::Number<> value)
{
    m_computedStyle.setTestLogicalPropertyGroupPhysicalHorizontal(value);
}

inline void RenderStyleProperties::setTestLogicalPropertyGroupPhysicalVertical(Style::Number<> value)
{
    m_computedStyle.setTestLogicalPropertyGroupPhysicalVertical(value);
}

inline void RenderStyleProperties::setLogicalTestLogicalPropertyGroupPhysicalHorizontal(Style::Number<> value)
{
    m_computedStyle.setLogicalTestLogicalPropertyGroupPhysicalHorizontal(value);
}

inline void RenderStyleProperties::setLogicalTestLogicalPropertyGroupPhysicalVertical(Style::Number<> value)
{
    m_computedStyle.setLogicalTestLogicalPropertyGroupPhysicalVertical(value);
}

} // namespace WebCore

