// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include <WebCore/StyleComputedStyleBase.h>

namespace WebCore {
namespace Style {

class ComputedStyleProperties : public ComputedStyleBase {
public:
    // 'test-render-style-storage-one-level-enum'
    inline Style::TestEnumeration testRenderStyleStorageOneLevelEnum() const;
    inline void setTestRenderStyleStorageOneLevelEnum(Style::TestEnumeration);
    static constexpr Style::TestEnumeration initialTestRenderStyleStorageOneLevelEnum();

    // 'test-render-style-storage-one-level-raw'
    inline Style::TestRaw testRenderStyleStorageOneLevelRaw() const;
    inline void setTestRenderStyleStorageOneLevelRaw(Style::TestRaw);
    static constexpr Style::TestRaw initialTestRenderStyleStorageOneLevelRaw();

    // 'test-render-style-storage-one-level-reference'
    inline const Style::Number<>& testRenderStyleStorageOneLevelReference() const;
    inline void setTestRenderStyleStorageOneLevelReference(Style::Number<>&&);
    static inline Style::Number<> initialTestRenderStyleStorageOneLevelReference();

    // 'test-render-style-storage-one-level-value'
    inline Style::Number<> testRenderStyleStorageOneLevelValue() const;
    inline void setTestRenderStyleStorageOneLevelValue(Style::Number<>);
    static inline Style::Number<> initialTestRenderStyleStorageOneLevelValue();

    // 'test-render-style-storage-two-level-enum'
    inline Style::TestEnumeration testRenderStyleStorageTwoLevelEnum() const;
    inline void setTestRenderStyleStorageTwoLevelEnum(Style::TestEnumeration);
    static constexpr Style::TestEnumeration initialTestRenderStyleStorageTwoLevelEnum();

    // 'test-render-style-storage-two-level-raw'
    inline Style::TestRaw testRenderStyleStorageTwoLevelRaw() const;
    inline void setTestRenderStyleStorageTwoLevelRaw(Style::TestRaw);
    static constexpr Style::TestRaw initialTestRenderStyleStorageTwoLevelRaw();

    // 'test-render-style-storage-two-level-reference'
    inline const Style::Number<>& testRenderStyleStorageTwoLevelReference() const;
    inline void setTestRenderStyleStorageTwoLevelReference(Style::Number<>&&);
    static inline Style::Number<> initialTestRenderStyleStorageTwoLevelReference();

    // 'test-render-style-storage-two-level-value'
    inline Style::Number<> testRenderStyleStorageTwoLevelValue() const;
    inline void setTestRenderStyleStorageTwoLevelValue(Style::Number<>);
    static inline Style::Number<> initialTestRenderStyleStorageTwoLevelValue();

    // 'test-logical-property-group-physical-horizontal'
    inline Style::Number<> testLogicalPropertyGroupPhysicalHorizontal() const;
    inline void setTestLogicalPropertyGroupPhysicalHorizontal(Style::Number<>);
    static inline Style::Number<> initialTestLogicalPropertyGroupPhysicalHorizontal();

    // 'test-logical-property-group-physical-vertical'
    inline Style::Number<> testLogicalPropertyGroupPhysicalVertical() const;
    inline void setTestLogicalPropertyGroupPhysicalVertical(Style::Number<>);
    static inline Style::Number<> initialTestLogicalPropertyGroupPhysicalVertical();

    // Logical getters and setters for 'test-group' properties of type 'axis'.
    inline Style::Number<> logicalTestLogicalPropertyGroupPhysicalHorizontal(WritingMode) const;
    inline Style::Number<> logicalTestLogicalPropertyGroupPhysicalVertical(WritingMode) const;
    inline Style::Number<> logicalTestLogicalPropertyGroupPhysicalHorizontal() const;
    inline Style::Number<> logicalTestLogicalPropertyGroupPhysicalVertical() const;
    inline void setLogicalTestLogicalPropertyGroupPhysicalHorizontal(Style::Number<>);
    inline void setLogicalTestLogicalPropertyGroupPhysicalVertical(Style::Number<>);

protected:
    ComputedStyleProperties(ComputedStyleProperties&&) = default;
    ComputedStyleProperties& operator=(ComputedStyleProperties&&) = default;

    ComputedStyleProperties(CreateDefaultStyleTag tag) : ComputedStyleBase { tag } { }
    ComputedStyleProperties(const ComputedStyleProperties& other, CloneTag tag) : ComputedStyleBase { other, tag } { }

    ComputedStyleProperties(ComputedStyleProperties& a, ComputedStyleProperties&& b) : ComputedStyleBase { a, WTF::move(b) } { }
};

} // namespace WebCore
} // namespace Style

