// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef COMPUTED_STYLE_PROPERTIES_SETTERS_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from StyleComputedStyle+SettersInlines.h."
#endif

#include "StyleComputedStyleProperties+SettersCustomInlines.h"

namespace WebCore {
namespace Style {

inline void ComputedStyleProperties::setTestRenderStyleStorageOneLevelEnum(Style::TestEnumeration value)
{
    if (value != static_cast<Style::TestEnumeration>(level1->testRenderStyleStorageOneLevelEnum))
        level1.access().testRenderStyleStorageOneLevelEnum = static_cast<unsigned>(value);
}

inline void ComputedStyleProperties::setTestRenderStyleStorageOneLevelRaw(Style::TestRaw value)
{
    if (value != Style::TestRaw::fromRaw(level1->testRenderStyleStorageOneLevelRaw))
        level1.access().testRenderStyleStorageOneLevelRaw = value.toRaw();
}

inline void ComputedStyleProperties::setTestRenderStyleStorageOneLevelReference(Style::Number<>&& value)
{
    if (value != level1->testRenderStyleStorageOneLevelReference)
        level1.access().testRenderStyleStorageOneLevelReference = WTF::move(value);
}

inline void ComputedStyleProperties::setTestRenderStyleStorageOneLevelValue(Style::Number<> value)
{
    if (value != level1->testRenderStyleStorageOneLevelValue)
        level1.access().testRenderStyleStorageOneLevelValue = value;
}

inline void ComputedStyleProperties::setTestRenderStyleStorageTwoLevelEnum(Style::TestEnumeration value)
{
    if (value != static_cast<Style::TestEnumeration>(level1->level2->testRenderStyleStorageTwoLevelEnum))
        level1.access().level2.access().testRenderStyleStorageTwoLevelEnum = static_cast<unsigned>(value);
}

inline void ComputedStyleProperties::setTestRenderStyleStorageTwoLevelRaw(Style::TestRaw value)
{
    if (value != Style::TestRaw::fromRaw(level1->level2->testRenderStyleStorageTwoLevelRaw))
        level1.access().level2.access().testRenderStyleStorageTwoLevelRaw = value.toRaw();
}

inline void ComputedStyleProperties::setTestRenderStyleStorageTwoLevelReference(Style::Number<>&& value)
{
    if (value != level1->level2->testRenderStyleStorageTwoLevelReference)
        level1.access().level2.access().testRenderStyleStorageTwoLevelReference = WTF::move(value);
}

inline void ComputedStyleProperties::setTestRenderStyleStorageTwoLevelValue(Style::Number<> value)
{
    if (value != level1->level2->testRenderStyleStorageTwoLevelValue)
        level1.access().level2.access().testRenderStyleStorageTwoLevelValue = value;
}

inline void ComputedStyleProperties::setTestLogicalPropertyGroupPhysicalHorizontal(Style::Number<> value)
{
    if (value != level1->testLogicalPropertyGroupPhysicalHorizontal)
        level1.access().testLogicalPropertyGroupPhysicalHorizontal = value;
}

inline void ComputedStyleProperties::setTestLogicalPropertyGroupPhysicalVertical(Style::Number<> value)
{
    if (value != level1->testLogicalPropertyGroupPhysicalVertical)
        level1.access().testLogicalPropertyGroupPhysicalVertical = value;
}

inline void ComputedStyleProperties::setLogicalTestLogicalPropertyGroupPhysicalHorizontal(Style::Number<> value)
{
    if (writingMode().isHorizontal())
        setTestLogicalPropertyGroupPhysicalHorizontal(WTF::move(value));
    else
        setTestLogicalPropertyGroupPhysicalVertical(WTF::move(value));
}

inline void ComputedStyleProperties::setLogicalTestLogicalPropertyGroupPhysicalVertical(Style::Number<> value)
{
    if (writingMode().isHorizontal())
        setTestLogicalPropertyGroupPhysicalVertical(WTF::move(value));
    else
        setTestLogicalPropertyGroupPhysicalHorizontal(WTF::move(value));
}

} // namespace WebCore
} // namespace Style

