// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef COMPUTED_STYLE_PROPERTIES_GETTERS_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from StyleComputedStyle+GettersInlines.h."
#endif

#include <WebCore/StyleComputedStyleProperties+GettersCustomInlines.h>

namespace WebCore {
namespace Style {

inline Style::TestEnumeration ComputedStyleProperties::testRenderStyleStorageOneLevelEnum() const
{
    return static_cast<Style::TestEnumeration>(level1->testRenderStyleStorageOneLevelEnum);
}

inline Style::TestRaw ComputedStyleProperties::testRenderStyleStorageOneLevelRaw() const
{
    return Style::TestRaw::fromRaw(level1->testRenderStyleStorageOneLevelRaw);
}

inline const Style::Number<>& ComputedStyleProperties::testRenderStyleStorageOneLevelReference() const
{
    return level1->testRenderStyleStorageOneLevelReference;
}

inline Style::Number<> ComputedStyleProperties::testRenderStyleStorageOneLevelValue() const
{
    return level1->testRenderStyleStorageOneLevelValue;
}

inline Style::TestEnumeration ComputedStyleProperties::testRenderStyleStorageTwoLevelEnum() const
{
    return static_cast<Style::TestEnumeration>(level1->level2->testRenderStyleStorageTwoLevelEnum);
}

inline Style::TestRaw ComputedStyleProperties::testRenderStyleStorageTwoLevelRaw() const
{
    return Style::TestRaw::fromRaw(level1->level2->testRenderStyleStorageTwoLevelRaw);
}

inline const Style::Number<>& ComputedStyleProperties::testRenderStyleStorageTwoLevelReference() const
{
    return level1->level2->testRenderStyleStorageTwoLevelReference;
}

inline Style::Number<> ComputedStyleProperties::testRenderStyleStorageTwoLevelValue() const
{
    return level1->level2->testRenderStyleStorageTwoLevelValue;
}

} // namespace WebCore
} // namespace Style

